### ISSUE TITLE
TV Support

### ISSUE THREAD

**Issue by nemchik** [piplongrun/CSM.bundle#6]
Would there be any way you would consider adding support for TV as well?

**Comment by piplongrun** [comment]
I wish I could add that, but it's just not possible.

**Comment by nemchik** [comment]
Any particular reason? I don't know python, but just looking at the source it looks like it would be very similar to movies.

**Comment by piplongrun** [comment]
The issue is not with the code of the agent, that would be quite easy to update to work with TV. The issue is with the backend code (the code running on api.tadata.me) that is unable to match TVDB ids to CSM data.

**Comment by nemchik** [comment]
Related to #2 would it be possible that you open source that code? Or would there be any way to just use IMDB ids for TV? (IMDB does have TV info, but I'm not sure if it has everything you need).

**Comment by nemchik** [comment]
That wording kind of increased suspicion around what your API actually does... I'm sure since I've already used it I've already played my part in whatever you're API does, but I'm going to disable it at this point anyway.

**Comment by piplongrun** [comment]
> That wording kind of increased suspicion around what your API actually does...

My API is just a simple "scraper" (not entirely, but I can't think of a better word for it) to provide my agent with required data without ddos'ing the source site (my own server is taking most of the hits). You are free to use the agent and/or the API however you like, and if you don't like any of it I encourage you to write your own agent/API/parsing code. I don't want to sound like an asshole, but that is just what it comes down to.

> I'm sure since I've already used it I've already played my part in whatever you're API does, but I'm going to disable it at this point anyway.

Please do what feels best for you. This is just a free service I created because of requests from the Plex community.

**Comment by nemchik** [comment]
You don't sound like an asshole, and I appreciate the explanation of what the API does. I would encourage that next time this conversation comes up you should lead with that information as opposed to shutting down inquiries about how it works.

For the moment I'm going to pursue other avenues, but I appreciate your work and I hope to see this project grow in the future.
